FROM php:8.1-fpm

RUN apt-get update && apt-get install -y libwebp-dev\
      apt-utils \
      libjpeg62-turbo-dev \
      libpq-dev \
      libpng-dev \
      libwebp-dev \
      libzip-dev \
      zip unzip \
      git && \
      docker-php-ext-install pdo_mysql && \
      docker-php-ext-install bcmath && \
      docker-php-ext-install zip && \
      docker-php-ext-configure gd --with-jpeg --with-webp=/usr/include/ && \
      docker-php-ext-install gd && \
      apt-get clean && \
      rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \

COPY ./_docker/app/php.ini /usr/local/etc/php/conf.d/php.ini

# Install composer
ENV COMPOSER_ALLOW_SUPERUSER=1
RUN curl -sS https://getcomposer.org/installer | php -- \
    --filename=composer \
    --install-dir=/usr/local/bin

# Install Node.js and npm
RUN curl -sL https://deb.nodesource.com/setup_16.x | bash - && \
    apt-get install -y nodejs && \
    npm install -g npm

WORKDIR /var/www
